winget install `
    Microsoft.PowerShell `
    Git.Git `
    astral-sh.uv `
    Oracle.JavaRuntimeEnvironment `
    AgileBits.1Password `
    Mozilla.Firefox `
    SublimeHQ.SublimeText.3 `
    7zip.7zip `
    Valve.Steam `
    Adobe.Acrobat.Reader.64-bit `
    Logitech.OptionsPlus `
    Ryochan7.DS4Windows `
    ViGEm.ViGEmBus `
    Guru3D.Afterburner `
    Guru3D.RTSS `
    CPUID.CPU-Z `
    TechPowerUp.GPU-Z `
    OCBase.OCCT.Personal `
    WinDirStat.WinDirStat `
    ClassicOldSong.Apollo `
    IrfanSkiljan.IrfanView `
    IrfanSkiljan.IrfanView.PlugIns `
    mpv.net `
    PeterPawlowski.foobar2000 `
    GIMP.GIMP.3 `
    Inkscape.Inkscape `
    BlenderFoundation.Blender `
    TheDocumentFoundation.LibreOffice
