#!/bin/sh

usermodmap=$HOME/.Xmodmap
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources
base16resources=$HOME/.config/base16-xresources/xresources/base16-default-dark-256.Xresources
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$base16resources" ] && xrdb -merge "$base16resources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
      [ -x "$f" ] && . "$f"
    done
    unset f
fi

setxkbmap pl

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

pulseaudio --start

xscreensaver -no-splash &
xss-lock -- /usr/bin/xscreensaver-command -lock &

volumeicon &
nm-applet &
# blueman-applet &
cbatticon &

dropbox &

exec awesome

